import Head from "next/head";

type PropsType = {
  info: string;
};
export default function About(props: PropsType) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h4>{props.info}</h4>
      </main>
    </>
  );
}
// export async function getStaticProps() {
//   // 只在build下执行 线上环境下不执行
//   return {
//     props: {
//       info: "About Page",
//     },
//   };
// }
export async function getServerSideProps() {
  console.log("每次请求都会执行");
  return {
    props: {
      info: "请求的数据1",
    },
  };
}
