import Head from "next/head";
import QuestionInput from "@/componnets/QuestionComponents/QuestionInput";
import QuestionRadio from "@/componnets/QuestionComponents/QuestionRadio";
type PropsType = {
  info: string;
};
export default function About(props: PropsType) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h4>{props.info}</h4>
        <form>
          <QuestionInput
            fe_id="123123"
            props={{ title: "你的姓名", placeholder: "请输入姓名" }}
          />
          <QuestionRadio
            fe_id="123ew23"
            props={{
              title: "姓名",
              options: [
                { value: "1", text: "1" },
                { value: "2", text: "2" },
              ],
              value: "1",
              isVertical: false,
            }}
          />
        </form>
      </main>
    </>
  );
}
// export async function getStaticProps() {
//   // 只在build下执行 线上环境下不执行
//   return {
//     props: {
//       info: "About Page",
//     },
//   };
// }
export async function getServerSideProps() {
  console.log("每次请求都会执行");
  return {
    props: {
      info: "请求的数据 1",
    },
  };
}
